#!/bin/bash

git checkout master
git fetch --all --prune
git pull --ff-only
git submodule update

git submodule foreach git fetch --all --prune
git submodule foreach git checkout master
git submodule foreach git pull --ff-only

clean-git-branches-remote

git submodule foreach clean-git-branches-remote
