#!/bin/bash

for f in `git diff --cached --name-status --diff-filter=ACM | grep -Ev "^D" | awk '{print $2}' | grep -E "ph(p|tml)" | grep -v "misc/migrations"`; do
    php-cs-fixer --fixers=-psr0,-phpdoc_params fix $f
done
